twilio:
  account_sid: AC5b2d93f99dfc61d1abff0a261c50d9e8
  auth_token: db0f7cb8ed0424b30b4d15179cb6b9f4
  trial_number: +16812023487
logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.glenvasa.Fitness.App1: DEBUG
    org.hibernate: ERROR
  file:
    name: C:/Users/glenv/Documents/Projects/Fitness-App-1/log/fitnessApp1.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"